name: CapturetheFlag
version: ${project.version}
main: me.yoursole.ctf.CTF
api-version: 1.18
authors: [Yoursole,SlashSlayer]
commands:
  start:
    description: Start Game
    usage: /<command>
    permission: op
  stop:
    description: Stop Game
    usage: /<command>
    permission: op
  scores:
    description: Get scores
    usage: /<command>
  timer:
    description: Start a timer
    usage: /<command> <clear | ms>
    permission: op
  togglechat:
    description: Toggles non operators from chatting
    usage: /<command>
    permission: op
  customitem:
    description: Gives a custom item
    usage: /<command> <itemID> [amount]
    permission: op
  top:
    description: Sends you to the highest block above you
    usage: /<command>
  test:
    description: test
    usage: /<command>